name: "Writer's Lifestyle"
favicon: null
layout_spectrum: 0.2514485658612102
typography_spectrum: 0.7015133101958781
title: "The Writer's Lifestyle"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7179084795061499
  lightness: 0.30020197480916977
  saturation: 0.7806446040049195
  rhythmicContrast: 0.7119960221461952
purpose: []
